### ISSUE TITLE
core.GdsImport(mygds) error with texttype

### ISSUE THREAD

**Issue by muab** [hohlraum/gdsCAD#40]
I cannot import my own gds. It seems to be some incompatibility with the record texttype. The traceback is:
Traceback (most recent call last):
  File "gds_tests.py", line 9, in <module>
    amarks = core.GdsImport(myfile)
  File "/usr/local/lib/python2.7/dist-packages/gdsCAD/core.py", line 1968, in GdsImport
    cell.add(create_element(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/gdsCAD/core.py", line 2172, in _create_text
    return Text(**kwargs)
TypeError: **init**() got an unexpected keyword argument 'texttype'

**Comment by muab** [comment]
it seems that this error has been corrected in version '0.5.0', which can be downloaded here, but is not updated in the python repository (last version there is '0.4.5').
