### ISSUE TITLE
DXF Import

### ISSUE THREAD

**Issue by floRoth** [hohlraum/gdsCAD#46]
Hi,
I am trying to import some dxf and convert it to gds. 
But always the same error message pops up:

I use just this code
dxf=core.DxfImport('jcsample.dxf', scale=1.0)

runfile('C:/Users/np/Documents/Python Scripts/untitled0.py', wdir='C:/Users/np/Documents/Python Scripts')
Traceback (most recent call last):

  File "<ipython-input-17-b93e2b56a4b1>", line 1, in <module>
    runfile('C:/Users/np/Documents/Python Scripts/untitled0.py', wdir='C:/Users/np/Documents/Python Scripts')

  File "C:\Program Files\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Program Files\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/np/Documents/Python Scripts/untitled0.py", line 17, in <module>
    if isinstance(e, dxfgrabber.entities.LWPolyline):

AttributeError: 'module' object has no attribute 'entities'

I am using Anaconda2 (Pyhton 2.4)

Thanks for the help
Flo

**Comment by hohlraum** [comment]
Fixed in 096e8bd.
