### ISSUE TITLE
Installation with Python 3.8.3. Error with get_version()

### ISSUE THREAD

**Issue by raghu1153** [hohlraum/gdsCAD#65]
Hi, I was able to install the gdsCAD with python 3 on my Linux machine. I was able to checkout to the 2and3 branch and run the python setup.py install command.

But when I try to install the package using the same command on Windows I am getting value error in the function get_version(). I am pasting the error message below. Also, I am unable to find any _version.py file in the gdsCAD directory.

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    version = get_version(),
  File "E:\myenv3\gdsCAD-2and3\git_version.py", line 101, in get_version
    raise ValueError("Cannot find the version number!")
ValueError: Cannot find the version number!

Can someone please help me with the installation on Python 3. Currently, I am trying to upgrade my software tool to Python 3 and I need gdsCAD for that.

**Comment by raghu1153** [comment]
I installed git on my Windows machine. I cloned the repo and checked out the 2and3 branch and did the python setup.py install. Now I am able to successfully install the package on Python 3.
