### ISSUE TITLE
Installtion problem in py38 enviroment with git: get_version()

### ISSUE THREAD

**Issue by gxyuta** [hohlraum/gdsCAD#67]
Hello Developers, I met a problem when I want to install gdsCAD in py38 environment. Here is the error I got, can you help me sort it out? Thanks a lot for your time.

```
(base) C:\Users\87490\Downloads\gdsCAD-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from git_version import sdist, get_version
  File "C:\Users\87490\Downloads\gdsCAD-master\git_version.py", line 107
    print get_version()
          ^
SyntaxError: invalid syntax
```

**Comment by ghost** [comment]
Hello guys, I think I have similar problem here. I get the error about using print command without parenthesis while installing gdsCAD-0.4.5 in py310 environment.
```
Collecting gdsCAD
  Using cached gdsCAD-0.4.5.tar.gz (450 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mk144174\OneDrive - Renishaw plc\Documents\Workspace\ChipFabricationViz\3dProcessModel\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mk144174\\AppData\\Local\\Temp\\pip-install-i9dhga27\\gdscad_14b7df7e3c414275ba3bb64df0ef828e\\setup.py'"'"'; __file__='"'"'C:\\Users\\mk144174\\AppData\\Local\\Temp\\pip-install-i9dhga27\\gdscad_14b7df7e3c414275ba3bb64df0ef828e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mk144174\AppData\Local\Temp\pip-pip-egg-info-371jbljc'
         cwd: C:\Users\mk144174\AppData\Local\Temp\pip-install-i9dhga27\gdscad_14b7df7e3c414275ba3bb64df0ef828e\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mk144174\AppData\Local\Temp\pip-install-i9dhga27\gdscad_14b7df7e3c414275ba3bb64df0ef828e\setup.py", line 4, in <module>
        from git_version import sdist, get_version
      File "C:\Users\mk144174\AppData\Local\Temp\pip-install-i9dhga27\gdscad_14b7df7e3c414275ba3bb64df0ef828e\git_version.py", line 107
        print get_version()
        ^^^^^^^^^^^^^^^^^^^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
    ----------------------------------------
```

The error is repeating for all version above gdsCAD-0.3.1. version.

**Comment by paulxshen** [comment]
its using python 2 . too bad this pkg is not maintained. try gdstk instead

**Comment by SengerM** [comment]
I think #69 fixes this issue.
